### ISSUE TITLE
Journal flooded with flooded with - cdc_ncm 2-2:2.0 enx5c857e3449d7: network connection: connected

### ISSUE THREAD

**Issue by mann1x** [wget/realtek-r8152-linux#21]
Debian 9 Stretch
Proxmox Kernel PVE 4.15.18-45

The latest drivers are still flooding the system with this connected message:

Aug 04 08:40:18 solidpc kernel: cdc_ncm 2-2:2.0 enx5c857e3449d7: 2500 mbit/s downlink 2500 mbit/s uplink
Aug 04 08:40:18 solidpc kernel: cdc_ncm 2-2:2.0 enx5c857e3449d7: network connection: connected
Aug 04 08:40:18 solidpc kernel: cdc_ncm 2-2:2.0 enx5c857e3449d7: 2500 mbit/s downlink 2500 mbit/s uplink
Aug 04 08:40:18 solidpc kernel: cdc_ncm 2-2:2.0 enx5c857e3449d7: network connection: connected
Aug 04 08:40:19 solidpc kernel: cdc_ncm 2-2:2.0 enx5c857e3449d7: 2500 mbit/s downlink 2500 mbit/s uplink
Aug 04 08:40:19 solidpc kernel: cdc_ncm 2-2:2.0 enx5c857e3449d7: network connection: connected
Aug 04 08:40:19 solidpc kernel: cdc_ncm 2-2:2.0 enx5c857e3449d7: 2500 mbit/s downlink 2500 mbit/s uplink
Aug 04 08:40:19 solidpc kernel: cdc_ncm 2-2:2.0 enx5c857e3449d7: network connection: connected
Aug 04 08:40:20 solidpc kernel: cdc_ncm 2-2:2.0 enx5c857e3449d7: 2500 mbit/s downlink 2500 mbit/s uplink
Aug 04 08:40:20 solidpc kernel: cdc_ncm 2-2:2.0 enx5c857e3449d7: network connection: connected
Aug 04 08:40:20 solidpc kernel: cdc_ncm 2-2:2.0 enx5c857e3449d7: 2500 mbit/s downlink 2500 mbit/s uplink
Aug 04 08:40:20 solidpc kernel: cdc_ncm 2-2:2.0 enx5c857e3449d7: network connection: connected
Aug 04 08:40:21 solidpc kernel: cdc_ncm 2-2:2.0 enx5c857e3449d7: 2500 mbit/s downlink 2500 mbit/s uplink
Aug 04 08:40:21 solidpc kernel: cdc_ncm 2-2:2.0 enx5c857e3449d7: network connection: connected
Aug 04 08:40:21 solidpc kernel: cdc_ncm 2-2:2.0 enx5c857e3449d7: 2500 mbit/s downlink 2500 mbit/s uplink
Aug 04 08:40:21 solidpc kernel: cdc_ncm 2-2:2.0 enx5c857e3449d7: network connection: connected

Same as:
https://bugzilla.redhat.com/show_bug.cgi?id=1851340

Had to roll back to 2.14 version to avoid it.

**Comment by hcartiaux** [comment]
Closed on the redhat bugzilla without a solution, so I will close this issue as well. 

In this repository, we just try to maintain the upstream driver against the latest linux kernel for our personal usage. We are absolutely not affiliated or supported by Realtek. We are not actually maintaining a patchset for all linux versions.
