### ISSUE TITLE
just a question

### ISSUE THREAD

**Issue by PierreGodetobii** [wget/realtek-r8152-linux#23]
I am trying to make and ubuntu 20 ipxe work and i need this driver so the initrd can boot with usb-c dongles (laptops), 
I extracted the initrd and placed this repo in the initrd folder structure but make is missing.. 

just throwing the question out. you can just close the ticket if my question is not relevant.

is there any way to install r8152 on an extracted initrd file?
I have also tried with an clean ubuntu 20 install on a desktop , then installing this module and use the initrd.img-version  but that just gives me kernel panic at booting the image.

**Comment by hcartiaux** [comment]
I hope you have found a solution, it's not really in the scope of this repository but I'll try to answer.

it is a general issue about how to include a module in the ubuntu initramfs and load it early in the boot sequence.
I think you should compile the module first, and then include the compiled module (r8152.ko) in the initramfs.

I don't have a Ubuntu system to verify, but apparently, you can use the config file [initramfs.conf](https://manpages.ubuntu.com/manpages/bionic/en/man5/initramfs.conf.5.html) to include a kernel module in the initand the command `update-initramfs`

Not sure if it can help, but I also had to create custom initrd in the past and I actually hacked my own scripts, quick and dirty way (probably outdated, but still interesting):

* Minimal self-contained initrd to boot in a rescue system: https://github.com/hcartiaux/make_rescue_initrd
* Generate a minimal system image and customized initrd for diskless servers (using iscsi): https://github.com/ULHPC/viridis-bootstrap
