### ISSUE TITLE
6.1 kernel API changes

### ISSUE THREAD

**Issue by ervinpopescu** [wget/realtek-r8152-linux#24]
`netif_napi_add` no longer takes napi poll weight as parameter, 6.1 defines it as macro: https://elixir.bootlin.com/linux/v6.1-rc1/source/include/linux/netdevice.h#L2547

https://elixir.bootlin.com/linux/v6.0.7/source/include/linux/netdevice.h#L2560
https://elixir.bootlin.com/linux/v6.1-rc1/source/include/linux/netdevice.h#L2562

Proposed patch: 

```patch
--- r8152.c	2022-11-07 14:40:54.243658136 +0200
+++ /usr/src/r8152-2.16.3.20220914/src/r8152.c	2022-11-07 14:39:59.070155889 +0200
@@ -17558,7 +17558,6 @@
 //		break;
 //	}
 
-
 	r8153b_mcu_spdown_en(tp, false);
 
 	ocp_data = ocp_read_word(tp, MCU_TYPE_PLA, PLA_EXTRA_STATUS);
@@ -18339,7 +18338,6 @@
 		cmd->autoneg = AUTONEG_DISABLE;
 	}
 
-
 	if (netif_running(netdev) && netif_carrier_ok(netdev)) {
 		u16 speed = rtl8152_get_speed(tp);
 
@@ -19202,7 +19200,6 @@
 		}
 		break;
 
-
 	case RTLTOOL_USB_OCP_WRITE_DWORD:
 		if (!tp->rtk_enable_diag && net_ratelimit())
 			netif_warn(tp, drv, netdev,
@@ -20708,10 +20705,14 @@
 
 	usb_set_intfdata(intf, tp);
 
+#if LINUX_VERSION_CODE < KERNEL_VERSION(6,1,0)
 	if (tp->support_2500full)
 		netif_napi_add(netdev, &tp->napi, r8152_poll, 256);
 	else
 		netif_napi_add(netdev, &tp->napi, r8152_poll, 64);
+#else /* LINUX_VERSION_CODE >= KERNEL_VERSION(6,1,0) */
+  netif_napi_add(netdev, &tp->napi, r8152_poll);
+#endif /* LINUX_VERSION_CODE < KERNEL_VERSION(6,1,0) */
 
 	ret = register_netdev(netdev);
 	if (ret != 0) {

```

**Comment by jayofdoom** [comment]
Hey; thanks for this. I'm looking to take this patch downstream in Gentoo; do you have an email you'd like me to credit? e.g. https://github.com/gentoo/gentoo/blob/master/net-misc/r8152/files/r8152-2.16.3-kernel-5.19-fix.patch 

Alternatively; if you have a fork with this commit it'd be trivial for me to turn that into a git patch. Thanks!

**Comment by ervinpopescu** [comment]
Hello there!

Yeah, I guess `ervin.popescu10@gmail.com` will do fine. And I'll try pushing a commit to a fork ASAP.

LE: [Done!](https://github.com/ervinpopescu/realtek-r8152-linux) Is this alright?

**Comment by hcartiaux** [comment]
Thanks for this patch. 

I have imported your commit in master. Do not hesitate to create a PR next time ;)
