### ISSUE TITLE
Shipping this in Gentoo

### ISSUE THREAD

**Issue by jayofdoom** [wget/realtek-r8152-linux#25]
Hey, heads up -- thanks for the patches! We're shipping them with the Gentoo package for this -> https://github.com/gentoo/gentoo/commit/0deab1e144a0472a21613080eb6204eb7d850026

I'll contribute back if we find or fix anything before you all do. Thanks o/

**Comment by hcartiaux** [comment]
Cool, thanks !

Yes, do not hesitate to create PRs ! 

I try to maintain this repo so that it will always work with the latest archlinux kernel on my own laptop. Yet, my responsiveness depends on my free time.

Best wishes and happy holidays ;)
